//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Allberg.Shooter.Windows {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DatasetCompetitors : DataSet {
        
        private ShootersDataTable tableShooters;
        
        public DatasetCompetitors() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DatasetCompetitors(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Shooters"] != null)) {
                    this.Tables.Add(new ShootersDataTable(ds.Tables["Shooters"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ShootersDataTable Shooters {
            get {
                return this.tableShooters;
            }
        }
        
        public override DataSet Clone() {
            DatasetCompetitors cln = ((DatasetCompetitors)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Shooters"] != null)) {
                this.Tables.Add(new ShootersDataTable(ds.Tables["Shooters"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableShooters = ((ShootersDataTable)(this.Tables["Shooters"]));
            if ((this.tableShooters != null)) {
                this.tableShooters.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DatasetCompetitors";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DatasetCompetitors.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableShooters = new ShootersDataTable();
            this.Tables.Add(this.tableShooters);
        }
        
        private bool ShouldSerializeShooters() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void ShootersRowChangeEventHandler(object sender, ShootersRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ShootersDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnId;
            
            private DataColumn columnName;
            
            private DataColumn columnClub;
            
            internal ShootersDataTable() : 
                    base("Shooters") {
                this.InitClass();
            }
            
            internal ShootersDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IdColumn {
                get {
                    return this.columnId;
                }
            }
            
            internal DataColumn NameColumn {
                get {
                    return this.columnName;
                }
            }
            
            internal DataColumn ClubColumn {
                get {
                    return this.columnClub;
                }
            }
            
            public ShootersRow this[int index] {
                get {
                    return ((ShootersRow)(this.Rows[index]));
                }
            }
            
            public event ShootersRowChangeEventHandler ShootersRowChanged;
            
            public event ShootersRowChangeEventHandler ShootersRowChanging;
            
            public event ShootersRowChangeEventHandler ShootersRowDeleted;
            
            public event ShootersRowChangeEventHandler ShootersRowDeleting;
            
            public void AddShootersRow(ShootersRow row) {
                this.Rows.Add(row);
            }
            
            public ShootersRow AddShootersRow(int Id, string Name, string Club) {
                ShootersRow rowShootersRow = ((ShootersRow)(this.NewRow()));
                rowShootersRow.ItemArray = new object[] {
                        Id,
                        Name,
                        Club};
                this.Rows.Add(rowShootersRow);
                return rowShootersRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                ShootersDataTable cln = ((ShootersDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new ShootersDataTable();
            }
            
            internal void InitVars() {
                this.columnId = this.Columns["Id"];
                this.columnName = this.Columns["Name"];
                this.columnClub = this.Columns["Club"];
            }
            
            private void InitClass() {
                this.columnId = new DataColumn("Id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnId);
                this.columnName = new DataColumn("Name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnName);
                this.columnClub = new DataColumn("Club", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnClub);
            }
            
            public ShootersRow NewShootersRow() {
                return ((ShootersRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new ShootersRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(ShootersRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ShootersRowChanged != null)) {
                    this.ShootersRowChanged(this, new ShootersRowChangeEvent(((ShootersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ShootersRowChanging != null)) {
                    this.ShootersRowChanging(this, new ShootersRowChangeEvent(((ShootersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ShootersRowDeleted != null)) {
                    this.ShootersRowDeleted(this, new ShootersRowChangeEvent(((ShootersRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ShootersRowDeleting != null)) {
                    this.ShootersRowDeleting(this, new ShootersRowChangeEvent(((ShootersRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveShootersRow(ShootersRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ShootersRow : DataRow {
            
            private ShootersDataTable tableShooters;
            
            internal ShootersRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableShooters = ((ShootersDataTable)(this.Table));
            }
            
            public int Id {
                get {
                    try {
                        return ((int)(this[this.tableShooters.IdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableShooters.IdColumn] = value;
                }
            }
            
            public string Name {
                get {
                    try {
                        return ((string)(this[this.tableShooters.NameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableShooters.NameColumn] = value;
                }
            }
            
            public string Club {
                get {
                    try {
                        return ((string)(this[this.tableShooters.ClubColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableShooters.ClubColumn] = value;
                }
            }
            
            public bool IsIdNull() {
                return this.IsNull(this.tableShooters.IdColumn);
            }
            
            public void SetIdNull() {
                this[this.tableShooters.IdColumn] = System.Convert.DBNull;
            }
            
            public bool IsNameNull() {
                return this.IsNull(this.tableShooters.NameColumn);
            }
            
            public void SetNameNull() {
                this[this.tableShooters.NameColumn] = System.Convert.DBNull;
            }
            
            public bool IsClubNull() {
                return this.IsNull(this.tableShooters.ClubColumn);
            }
            
            public void SetClubNull() {
                this[this.tableShooters.ClubColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ShootersRowChangeEvent : EventArgs {
            
            private ShootersRow eventRow;
            
            private DataRowAction eventAction;
            
            public ShootersRowChangeEvent(ShootersRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public ShootersRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
